# Generated by Django 3.1.2 on 2020-10-22 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default=None, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('image', models.FileField(blank=True, upload_to='product_image')),
                ('price', models.PositiveIntegerField()),
                ('warrenty', models.CharField(default='30 Days', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
