# Generated by Django 3.1.2 on 2020-10-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default=None, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('warrenty', models.CharField(default='30 Days', max_length=10)),
                ('seller', models.EmailField(max_length=254, null=True)),
                ('description', models.TextField(default=models.CharField(blank=True, max_length=30))),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
