# Generated by Django 3.1 on 2020-09-11 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_both', models.BooleanField(default=False)),
                ('is_first_login', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, upload_to='Images/ProfileIMG')),
                ('full_name', models.CharField(max_length=50)),
                ('shop_name', models.CharField(blank=True, max_length=50)),
                ('phone_num', models.PositiveIntegerField(unique=True)),
                ('phone_num2', models.PositiveIntegerField()),
                ('aadhar', models.CharField(blank=True, max_length=16, unique=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('pincode', models.PositiveSmallIntegerField(default=0)),
                ('shop_established_date', models.DateField(blank=True, null=True)),
                ('shop_img', models.ImageField(blank=True, upload_to='Images/ShopsIMG')),
                ('shop_type', models.CharField(default='Retailer', max_length=15)),
                ('gst_num', models.CharField(blank=True, max_length=15)),
                ('available_services', models.CharField(blank=True, max_length=200)),
                ('average_price', models.PositiveIntegerField(default=0)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=230)),
                ('image', models.ImageField(upload_to='Images/Products/%Y/%m/%d')),
                ('is_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_app.merchantaccount')),
            ],
        ),
    ]
