# Generated by Django 3.1 on 2020-09-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='image',
            field=models.ImageField(upload_to='Products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='merchantaccount',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='ProfileIMG'),
        ),
        migrations.AlterField(
            model_name='merchantaccount',
            name='shop_img',
            field=models.ImageField(blank=True, upload_to='ShopsIMG'),
        ),
    ]
